/* -- F. Graphics Library (FGL) --
 * File: logo.hpp
 *
 * This code file generated by the img_to_fgl.py script
 * contains the contents of an image file adapted to
 * using with FGL
 *
 * Original image file: logo.png
 * FGL image format: ARGB1555
 * Generation date (Y-M-D): 2021-10-26
 */
#ifndef LOGO_HPP
#define LOGO_HPP

#include <image.hpp>

Image *get_logo_image();

#endif
