/* -- F. Graphics Library (FGL) --
 * File: space6.hpp
 *
 * This code file generated by the img_to_fgl.py script
 * contains the contents of an image file adapted to
 * using with FGL
 *
 * Original image file: space_6.png
 * FGL image format: K8
 * Generation date (Y-M-D): 2021-10-26
 */
#ifndef SPACE6_HPP
#define SPACE6_HPP

#include <image.hpp>

Image *get_space6_img();

#endif
