/* -- F. Graphics Library (FGL) --
 * File: space9.hpp
 *
 * This code file generated by the img_to_fgl.py script
 * contains the contents of an image file adapted to
 * using with FGL
 *
 * Original image file: space_9.png
 * FGL image format: K8
 * Generation date (Y-M-D): 2021-10-26
 */
#ifndef SPACE9_HPP
#define SPACE9_HPP

#include <image.hpp>

Image *get_space9_img();

#endif
