/* -- F Graphics Library --
 * Code generated by the fglttf.py script
 * Font name: liberation_sans_12px
 * Generation date (Y-M-D): 2021-11-01
 */

#ifndef LIBERATION_SANS_12PX_HPP
#define LIBERATION_SANS_12PX_HPP
#include <font.hpp>
#include <glyph.hpp>

Font *get_liberation_sans_12px();

#endif