/* -- F. Graphics Library (FGL) --
 * File: butterfly.hpp
 *
 * This code file generated by the img_to_fgl.py script
 * contains the contents of an image file adapted to
 * using with FGL
 *
 * Original image file: butterfly.png
 * FGL image format: ARGB1555
 * Generation date (Y-M-D): 2021-11-01
 */
#ifndef BUTTERFLY_HPP
#define BUTTERFLY_HPP

#include <image.hpp>

Image *get_butterfly_image();

#endif
