python fglimg.py samples/space_1.png space1 --dir images --fname get_space1_img --format K8 --resize 32 32
python fglimg.py samples/space_2.png space2 --dir images --fname get_space2_img --format K8 --resize 32 32
python fglimg.py samples/space_3.png space3 --dir images --fname get_space3_img --format K8 --resize 32 32
python fglimg.py samples/space_4.png space4 --dir images --fname get_space4_img --format K8 --resize 32 32
python fglimg.py samples/space_5.png space5 --dir images --fname get_space5_img --format K8 --resize 32 32
python fglimg.py samples/space_6.png space6 --dir images --fname get_space6_img --format K8 --resize 32 32
python fglimg.py samples/space_7.png space7 --dir images --fname get_space7_img --format K8 --resize 32 32
python fglimg.py samples/space_8.png space8 --dir images --fname get_space8_img --format K8 --resize 32 32
python fglimg.py samples/space_9.png space9 --dir images --fname get_space9_img --format K8 --resize 32 32
python fglimg.py samples/space_10.png space10 --dir images --fname get_space10_img --format K8 --resize 32 32
