/* -- F Graphics Library --
 * Code generated by the fglttf.py script
 * Font name: liberation_serif_18px
 * Generation date (Y-M-D): 2021-11-01
 */

#ifndef LIBERATION_SERIF_18PX_HPP
#define LIBERATION_SERIF_18PX_HPP
#include <font.hpp>
#include <glyph.hpp>

Font *get_liberation_serif_18px();

#endif