/* -- F. Graphics Library (FGL) --
 * File: space10.hpp
 *
 * This code file generated by the img_to_fgl.py script
 * contains the contents of an image file adapted to
 * using with FGL
 *
 * Original image file: space_10.png
 * FGL image format: K8
 * Generation date (Y-M-D): 2021-10-26
 */
#ifndef SPACE10_HPP
#define SPACE10_HPP

#include <image.hpp>

Image *get_space10_img();

#endif
