/* -- F. Graphics Library (FGL) --
 * File: logo_white.hpp
 *
 * This code file generated by the img_to_fgl.py script
 * contains the contents of an image file adapted to
 * using with FGL
 *
 * Original image file: logo-white.png
 * FGL image format: ARGB1555
 * Generation date (Y-M-D): 2021-11-01
 */
#ifndef LOGO_WHITE_HPP
#define LOGO_WHITE_HPP

#include <image.hpp>

Image *get_logo_white();

#endif
